spring:
    application:
        name: micro-discovery-server

server:
    port: 8761

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        server:
            waitTimeInMsWhenSyncEmpty: 0
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

logging:
    level:
        com.netflix: 'WARN'
        org.springframework.cloud: 'WARN'
